accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('products/', views.product_list, name='product_list'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order/create/', views.order_create, name='order_create'),
    path('page/<slug:slug>/', views.page_detail, name='page_detail'),
]

mycom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# tambahkan model Category, Product, Order, OrderItem, Costumer
from django.db import models
from django.utils import timezone
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='product_images/')

    def __str__(self):
        return self.name

class Order(models.Model):
    customer_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    address = models.TextField()
    products = models.ManyToManyField(Product, through='OrderItem')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Order #{self.id}"



class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)  # Adding the quantity field
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)  # Calculated subtotal based on quantity and product price

    def save(self, *args, **kwargs):
        # Calculate subtotal based on product price and quantity
        self.subtotal = self.product.price * self.quantity
        super().save(*args, **kwargs)

class Customer(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    address = models.TextField()

    def __str__(self):
        return self.name
    

class Page(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='page_images/')
    created = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(unique=True, max_length=255)
    is_published = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
#DevelopHermantoXYZ

accounts/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    # Tambahkan field quantity ke dalam form
    quantity = forms.IntegerField(min_value=1, initial=1)

    class Meta:
        model = Order
        fields = ['customer_name', 'phone_number', 'address', 'products', 'total_price', 'quantity']

accounts/views.py
from django.shortcuts import render
#tambahkan product dalam views.py
from .models import Product, Order, Page
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import OrderForm

#Product List
def product_list(request):
    products = Product.objects.all()
    return render(request, 'product_list.html', {'products': products})

# Menampilkan Product list di home.html
def home(request):
    products = Product.objects.all()
    return render(request, 'home.html', {'products': products})

# Menampilkan Product Detail
def product_detail(request, product_id):
    # Dapatkan objek produk berdasarkan ID atau tampilkan 404 jika tidak ditemukan
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'product_detail.html', {'product': product})


def order_list(request):
    orders = Order.objects.all()
    return render(request, 'order_list.html', {'orders': orders})

def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order_detail.html', {'order': order})

# Menampilkan order Create
def order_create(request):
    product_id = request.GET.get('product_id')
    product = get_object_or_404(Product, id=product_id)
    
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            total_price = product.price * quantity  # Hitung total harga
            order = form.save(commit=False)
            order.total_price = total_price
            order.save()  # Simpan objek Order terlebih dahulu
            order.products.add(product, through_defaults={'quantity': quantity})
            return redirect('order_detail', order_id=order.id)
    else:
        form = OrderForm(initial={'products': [product]})
    return render(request, 'order_create.html', {'form': form})

# Menampilkan Page Detail
def page_detail(request, slug):
    page = get_object_or_404(Page, slug=slug)
    return render(request, 'page_detail.html', {'page': page})

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ainalstore</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .judul {
            color: white;
            text-align: center;
            padding: 30px 0px; 
            display: inline-block; 
            width: max-content; 
            background-color: rgb(45, 28, 201); 
            margin: 12; 
            box-sizing: border-box;
        }
        body {
            background-color: rgb(67, 36, 207);
        }
        .navbar {
            background-color: #e7e8e3;
        }
        .navbar a {
            color: #4b15c7;
            padding: 14px 20px;
        }
        .navbar a:hover {
            background-color: #ddd;
            color: rgb(8, 11, 182);
        }
        .foto1 {
            width: 30%;
            display: block;
            margin: 0 auto;
        }
        .list-produk {
            list-style: none;
        }
        .judul-produk {
            color: rgb(10, 24, 146);
        }
    </style>
</head>
<body>

    <header>
        <header style="background-color: rgb(45, 15, 155);"></header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand" href="#" style="color: rgb(24, 49, 190);">Ainalstore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#detail" style="color: blue;">Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#keranjang" style="color: blue;">Keranjang</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#checkout" style="color: blue;">Checkout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#kontak" style="color: blue;">Kontak</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    

    <h1 class="judul">Welcome to Ainalstore!</h1>
    
    <div class="container">
        <div class="row">
            {% for product in products %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" src="{{ product.image.url }}" alt="Product Image">
                    <div class="card-body">
                        <h2 class="card-title"style="color: green;">{{ product.name }}</h2>
                        <p class="card-text" style="color: blue;">Category: {{ product.category }}</p>
                        <p class="card-text" style="color: blue;">Price: Rp{{ product.price }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'product_detail' product_id=product.id %}" class="btn btn-sm btn-outline-secondary">View Details</a>
                                <!-- Tambahkan detail lainnya sesuai kebutuhan -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
    
    <footer class="footer bg-light">
        <div class="container">
            <nav class="menu">
                <a href="#" style="color: blue;">Home</a>
                <a href="#" style="color: blue;">Detail</a>
                <a href="#" style="color: blue;">Keranjang</a>
                <a href="#" style="color: blue;">Checkout</a>
                <a href="#" style="color: blue;">Kontak</a>
            </nav>
        </div>
        <style>
            .footer {
                padding: 20px 0; 
                text-align: center; 
            }
            .menu a {
                margin: 0 10px; 
                text-decoration: none; 
            }
        </style>
    </footer>
    

    <h1 class="alamat">Kantor Pusat Ainalstore</h2>
        <div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15894.248113082938!2d119.43502166159666!3d-5.1739161512510465!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dbee291f084750b%3A0xa4f4abfdff834d4b!2sUniversitas%20Negeri%20Makassar!5e0!3m2!1sid!2sid!4v1713709153170!5m2!1sid!2sid" width="1200" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" class="alamat"></iframe>
        </div>
    
</body>
</html>

templates/order_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Form</title>
</head>
<body>
    <h1>Create Order</h1>
    <form id="order-form" method="post">
        {% csrf_token %}
        <label for="id_customer_name">Customer Name:</label>
        <input type="text" name="customer_name" id="id_customer_name" required>
        <br>
        <label for="id_phone_number">Phone Number:</label>
        <input type="text" name="phone_number" id="id_phone_number" required>
        <br>
        <label for="id_address">Address:</label>
        <textarea name="address" id="id_address" required></textarea>
        <br>
        <label for="id_products">Products:</label>
        <select name="products" id="id_products" multiple required>
            {% for product in form.products.field.queryset %}
                <option value="{{ product.id }}" data-price="{{ product.price }}">{{ product.name }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="id_quantity">Quantity:</label>
        <input type="number" name="quantity" id="id_quantity" min="1" value="1" required>
        <br>
        <label for="id_total_price">Total Price:</label>
        <input type="number" name="total_price" id="id_total_price" min="0" step="0.01" required readonly>
        <br>
        <button type="submit">Submit Order</button>
    </form>

    <script>
        // Ambil elemen-elemen yang diperlukan dari formulir
        const productsSelect = document.getElementById('id_products');
        const quantityInput = document.getElementById('id_quantity');
        const totalPriceInput = document.getElementById('id_total_price');

        // Tambahkan event listener untuk menghitung total harga setiap kali produk dipilih atau jumlah produk diubah
        productsSelect.addEventListener('change', calculateTotalPrice);
        quantityInput.addEventListener('input', calculateTotalPrice);

        function calculateTotalPrice() {
            let total = 0;
            // Loop melalui opsi yang dipilih dan tambahkan harga produk ke total
            for (const option of productsSelect.selectedOptions) {
                total += parseFloat(option.dataset.price);
            }
            // Hitung total harga berdasarkan harga produk dan jumlah produk
            total *= parseInt(quantityInput.value);
            // Tampilkan total harga di dalam input total_price
            totalPriceInput.value = total.toFixed(2);
        }
    </script>
</body>
</html>

templates/order_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Detail</title>
</head>
<body>
    <h1>Order Detail</h1>
    <h2>Order ID: {{ order.id }}</h2>
    <p>Customer: {{ order.customer_name }}</p>
    <p>Address: {{ order.address }}</p>
    <p>Total Price: ${{ order.total_price }}</p>
    <p>Created At: {{ order.created_at }}</p>
    <h3>Order Items:</h3>
    <ul>
        {% for order_item in order.orderitem_set.all %}
            <li>
                <p>Product: {{ order_item.product.name }}</p>
                <p>Quantity: {{ order_item.quantity }}</p>  
            </li>
        {% endfor %}
    </ul>
    <p>Total Order Price: ${{ order.total_price }}</p> <!-- Add this line to display total order price -->
</body>
</html>

templates/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order List</title>
</head>
<body>
    <h1>Order List</h1>
    <ul>
        {% for order in orders %}
            <li>
                <h2>Order ID: {{ order.id }}</h2>
                <p>Customer: {{ order.customer }}</p>
                <p>Total Price: ${{ order.total_price }}</p>
                <p>Created At: {{ order.created_at }}</p>
                <!-- Tambahkan detail lainnya sesuai kebutuhan -->
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/page_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page.title }}</title>
</head>
<body>
    <h1>{{ page.title }}</h1>
    <p>{{ page.content }}</p>
   

    <img src="{{ page.image.url }}" alt="{{ page.title }}">
    
    <!-- tambahkan lebih banyak konten halaman sesuai kebutuhan -->
</body>
</html>

templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.name }}</title>
</head>
<body>
    <h1>{{ product.name }}</h1>
    <p>Category: {{ product.category }}</p>
    <p>Price: ${{ product.price }}</p>
    <img src="{{ product.image.url }}" alt="{{ product.name }}">
    <p>Description: {{ product.description }}</p>
    <a href="{% url 'order_create' %}?product_id={{ product.id }}">Order Now</a>
    <!-- Tambahkan detail lainnya sesuai kebutuhan -->
</body>
</html>

templates/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
</head>
<body>
    <h1>Product List</h1>
    <ul>
        {% for product in products %}
            <li>
                <h2>{{ product.name }}</h2>
                <p>Category: {{ product.category }}</p>
                <p>Price: ${{ product.price }}</p>
                <a href="{% url 'product_detail' product_id=product.id %}">View Details</a>
                <!-- Tambahkan detail lainnya sesuai kebutuhan -->
            </li>
        {% endfor %}
    </ul>
    
</body>
</html>